name: 🪲 Bug Report
description: Open an issue regarding a bug of LUPA
title: "[BUG-REPORT] Title of the bug found"
labels: ["bug"]

#milestones
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        #### Thanks for taking the time to fill out this bug report 🤗
        ------
        Make sure there aren't any open/closed issues for this topic 😃

  - type: dropdown
    id: categories
    attributes:
      label: Categories
      description: Categories of the bug found
      multiple: true
      options:
        - "CLI - Migrations"
        - "CLI - Generate Schema CSV"
        - "CLI - Add Partition"
        - "CLI - Fill Profile History"
        - "Airflow/Scheduler"
        - "Notebook"
        - "DataQuality / GreatExpectation"
        - "Documentation"
        - "Spark Configuration"
        - "Profiles / Panels"
        - "Feature-Factory API"
        - "CI/CD"
    validations: 
      required: true

  - type: checkboxes
    id: environments
    attributes:
      label: Environments
      description: Bug found in environments
      options:
        - label: FEATURE BRANCH
        - label: DEV
        - label: STAGE
        - label: PRD

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give us a brief description of what happened and what should have happened
      placeholder: |
        Description of the bug
        More description
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
    
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  
  - type: dropdown
    id: critical
    attributes:
        label: Critical
        description: Is this bug critical for your squad?
        options:
          - "No"
          - "Yes"
    validations: 
      required: true

  - type: dropdown
    id: fix
    attributes:
        label: Fix
        description: Do you have na idea of how to fix it?
        options:
          - "No"
          - "Yes"
    validations: 
      required: true
  
  - type: textarea
    id: known-fix
    attributes:
      label: Known Fix
      description: Feel free to propose your fix here
      render: Markdown

  - type: dropdown
    id: pull-request
    attributes:
        label: Pull Request
        description: Are you willing to submit a PR?
        options:
          - "No"
          - "Yes"
    validations: 
      required: true
