name: 🪲 Bug Report
description: Open an issue regarding a bug of LUPA
title: "[BUG-REPORT] Title of the bug found"
labels: ["bug"]

#milestones
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        #### Thanks for taking the time to fill out this bug report 🤗 Plase don't forget to select the apropriate labels for the issue in the side bar
        ------
        Make sure there aren't any open/closed issues for this topic 😃

  - type: dropdown
    id: categories
    attributes:
      label: Categories
      description: Categories of the bug found (select all that apply)
      multiple: true
      options:
        - "CLI"
        - "Airflow"
        - "Notebook"
        - "GreatExpectation"
        - "Documentation"
        - "Spark Configuration"
        - "Profiles / Panels"
        - "Feature-Factory API"
        - "CI/CD"
    validations:
      required: true

  - type: checkboxes
    id: version
    attributes:
      label: Version
      description: In which version of LUPA was the bug found (select all that apply)
      options:
        - label: FEATURE BRANCH
        - label: DEV
        - label: STAGE
        - label: PRD

  - type: input
    id: branch
    attributes:
      label: Branch
      description: If needed, you can specify here the name of your branch.
      placeholder: bug-lupa-feature-branch-data-product-squad

  - type: input
    id: repo
    attributes:
      label: Repository
      description: Please provide the Repo's link of the code where you are having the bug?
      placeholder: https://github.com/nosportugal/dsi-de-data-product-relapses/blob/dev/orchestration-tools/orchestration/lupa/profiles/active_bundles/main.py

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: |
        Give us a brief description of what and how it happened and what was expected to have happened
      placeholder: |
        What were trying to do before the bug?
        What did you observe after the bug happened?
        What were you expecting to observe instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the behavior, include some code to reproduce when possibe
      value: |
        <!---
        This comment will not render. Start by providing some initial steps that should be followed
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        -->

        <!---
        Some line that you can run to generate the error 
        ```shell 
        python manage.py generate_schema_csv -n EXAMPLE_PROFILE -p 19000101
        ```
        -->

        <!---
        Some code that is called that triggers the issue
        ```python
        import lupa
        x = 'a' + 'b'
        print(x)
        ```
        -->

        <!---
        Or a link to the same lines of code
        https://github.com/Gustavo-1300/Issuses_template/blob/8edcee68b01f4a58a48d1c387d4cec9d1770ed0e/example/test.py#L1-L3
        -->
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output (alternatively, you can add the log file to "Description of the bug"). This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: Python Enviroment
      description: |
        Please provide the requirements to replicate the python enviroment where the bug occured (you can use the following command pip3 freeze > requirements.txt)
    validations:
      required: false

  - type: dropdown
    id: critical
    attributes:
      label: Critical
      description: Is this bug critical for your squad?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: fix
    attributes:
      label: Fix
      description: Do you have an idea of how to fix it?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: known-fix
    attributes:
      label: Known Fix
      description: Feel free to propose your fix here
      value: |
        <!---
        This comment will not render. You should provide both the location of the code where the bug happens, e.g.:

        The bug can be found in these lines:
        https://github.com/Gustavo-1300/Issuses_template/blob/8edcee68b01f4a58a48d1c387d4cec9d1770ed0e/example/test.py#L1-L3
        -->

        <!---
        Also include your suggestion, preferably in a code snippet:
        ```python
        import numpy as np
        x = np.array([1,3])
        ```
        -->
    validations:
      required: false

  - type: dropdown
    id: pull-request
    attributes:
      label: Pull Request
      description: Are you willing to submit a PR (with the help of Squad Enablement)?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
