name: ✨ Feature Request
description: Request a new feature for LUPA
title: "[FEATURE-REQUEST] Title of the new feature"
labels: ["feature"]

#milestones
#assignees:
body:
  - type: markdown
    attributes:
      value: |
        #### Thanks for taking the time to fill out this form for the feature request 🤗 Plase don't forget to select the apropriate labels in the side bar
        ------
        Make sure there aren't any open/closed issues for this feature 😃

  - type: dropdown
    id: categories
    attributes:
      label: Categories
      description: On which categories you want to apply this new feature?
      multiple: true
      options:
        - "CLI"
        - "Airflow"
        - "Notebook"
        - "GreatExpectation"
        - "Documentation"
        - "Spark Configuration"
        - "Profiles / Panels"
        - "Feature-Factory API"
        - "CI/CD"
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: Branch
      description: In which branch you want to apply this new feature?
      placeholder: feature-banch-name, development, stage, and/or production

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the feature
      description: |
        Give us a brief description of what this new feature could solve and/or LUPA is not doing
      placeholder: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        **Additional context**
        Add any other context or screenshots about the feature request here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output of this new feature. This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: false

  - type: textarea
    id: env
    attributes:
      label: Python Enviroment
      description: |
        Please provide the requirements to replicate the python enviroment where the bug occured (you can use the following command pip3 freeze > requirements.txt)
    validations:
      required: false

  - type: dropdown
    id: critical
    attributes:
      label: Critical
      description: Is this feature critical for your squad?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: feature
    attributes:
      label: Feature
      description: Do you have an idea on how to implement this feature?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: known-feature
    attributes:
      label: Known Feature
      description: Feel free to propose the code (or some part of it) for the feature here
      value: |
        <!---
        Also include your suggestion, preferably in a code snippet:
        ```python
        import numpy as np
        x = np.array([1,3])
        ```
        -->
    validations:
      required: false

  - type: dropdown
    id: pull-request
    attributes:
      label: Pull Request
      description: Are you willing to submit a PR (with the help of Squad Enablement)?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
